"""
models.py - Data Classes for NetWatch
=======================================

Type-safe data structures shared across all database modules.
Using dataclasses keeps the code self-documenting and avoids
passing raw dicts everywhere.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Optional, List, Dict, Any


@dataclass
class PacketData:
    """
    A single parsed packet coming from Phase 2's PacketProcessor.

    Fields map 1-to-1 with the columns in ``traffic_summary``.
    """
    timestamp: datetime = field(default_factory=datetime.now)
    source_ip: str = "unknown"
    dest_ip: str = "unknown"
    source_mac: Optional[str] = None
    dest_mac: Optional[str] = None
    source_port: Optional[int] = None
    dest_port: Optional[int] = None
    protocol: str = "UNKNOWN"
    raw_protocol: Optional[str] = None
    bytes_transferred: int = 0
    direction: str = "unknown"          # upload | download | unknown
    device_name: Optional[str] = None
    vendor: Optional[str] = None
    dest_vendor: Optional[str] = None   # gateway / hotspot vendor

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        if isinstance(d.get("timestamp"), datetime):
            d["timestamp"] = d["timestamp"].strftime("%Y-%m-%d %H:%M:%S")
        return d


@dataclass
class Device:
    """A network device identified by its MAC address."""
    mac_address: str
    ip_address: str
    hostname: Optional[str] = None
    device_name: Optional[str] = None
    vendor: Optional[str] = None
    first_seen: Optional[str] = None
    last_seen: Optional[str] = None
    total_bytes: int = 0
    bytes_sent: int = 0
    bytes_received: int = 0
    packet_count: int = 0
    is_local: bool = True

    # Formatted helpers (populated after query)
    total_bytes_formatted: str = ""
    today_bytes: int = 0
    today_sent: int = 0
    today_received: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class Alert:
    """A system alert generated by the anomaly detector or threshold checks."""
    id: Optional[int] = None
    timestamp: Optional[str] = None
    alert_type: str = "anomaly"
    severity: str = "info"              # info | low | medium | warning | high | critical
    message: str = ""
    details: Optional[str] = None
    source_ip: Optional[str] = None
    dest_ip: Optional[str] = None
    resolved: bool = False
    resolved_at: Optional[str] = None
    resolved_by: Optional[str] = None
    acknowledged: bool = False
    acknowledged_at: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["resolved"] = int(d["resolved"])
        d["acknowledged"] = int(d["acknowledged"])
        return d


@dataclass
class TrafficStats:
    """Real-time traffic statistics snapshot."""
    bandwidth_bps: float = 0.0
    bandwidth_mbps: float = 0.0
    active_devices: int = 0
    packets_per_second: float = 0.0
    total_bytes_today: int = 0
    total_packets_today: int = 0
    timestamp: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class HealthScore:
    """Network health score and its contributing factors."""
    score: int = 100
    status: str = "good"                # good | warning | critical | unknown
    factors: List[str] = field(default_factory=list)
    device_count: int = 0
    traffic_count: int = 0
    critical_alerts: int = 0
    warning_alerts: int = 0
    timestamp: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
