--
-- schema.sql - NetWatch Database Schema
-- =======================================
--
-- This file defines the database schema for NetWatch.
-- Production-ready schema with full table definitions, indexes, and constraints.
--

-- =============================================================================
-- DEVICES TABLE
-- =============================================================================
-- Stores information about devices seen on the network.
-- Each unique MAC address gets one record. Updated as traffic is captured.
-- Phase 1 migration 008: MAC-primary keying replaces IP-primary keying.

CREATE TABLE IF NOT EXISTS devices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    mac_address TEXT NOT NULL UNIQUE,
    ip_address TEXT DEFAULT NULL,
    ipv4_address TEXT DEFAULT NULL,
    ipv6_address TEXT DEFAULT NULL,
    hostname TEXT DEFAULT NULL,
    device_name TEXT DEFAULT NULL,
    vendor TEXT DEFAULT NULL,
    first_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_bytes_sent INTEGER DEFAULT 0,
    control_bytes_sent INTEGER DEFAULT 0,
    total_bytes_received INTEGER DEFAULT 0,
    control_bytes_received INTEGER DEFAULT 0,
    total_packets INTEGER DEFAULT 0,
    is_local INTEGER DEFAULT 0,
    device_type TEXT DEFAULT 'unknown',
    notes TEXT DEFAULT NULL,
    detected_mode TEXT DEFAULT NULL,
    active_mode TEXT DEFAULT NULL
);

-- =============================================================================
-- TRAFFIC_SUMMARY TABLE
-- =============================================================================
-- Stores individual packet/connection records for traffic analysis.
-- This is the main table for bandwidth and protocol analysis.

CREATE TABLE IF NOT EXISTS traffic_summary (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_ip TEXT NOT NULL,
    dest_ip TEXT NOT NULL,
    source_mac TEXT DEFAULT NULL,
    dest_mac TEXT DEFAULT NULL,
    source_port INTEGER DEFAULT NULL,
    dest_port INTEGER DEFAULT NULL,
    protocol TEXT NOT NULL DEFAULT 'UNKNOWN',
    raw_protocol TEXT DEFAULT NULL,
    bytes_transferred INTEGER NOT NULL DEFAULT 0,
    packets_count INTEGER DEFAULT 1,
    direction TEXT DEFAULT 'unknown',
    is_control INTEGER DEFAULT 0,
    session_id TEXT DEFAULT NULL,
    device_name TEXT DEFAULT NULL,
    vendor TEXT DEFAULT NULL
);

-- =============================================================================
-- ALERTS TABLE
-- =============================================================================
-- Stores alerts generated by the anomaly detection system.
-- Supports different severity levels and resolution tracking.

CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alert_type TEXT NOT NULL CHECK(alert_type IN ('bandwidth', 'anomaly', 'device_count', 'health', 'protocol', 'connection', 'security', 'new_device', 'custom')),
    severity TEXT NOT NULL CHECK(severity IN ('info', 'low', 'medium', 'warning', 'high', 'critical')),
    message TEXT NOT NULL,
    details TEXT DEFAULT NULL,
    source_ip TEXT DEFAULT NULL,
    dest_ip TEXT DEFAULT NULL,
    resolved INTEGER DEFAULT 0,
    resolved_at TIMESTAMP DEFAULT NULL,
    resolved_by TEXT DEFAULT NULL,
    acknowledged INTEGER DEFAULT 0,
    acknowledged_at TIMESTAMP DEFAULT NULL,
    incident_id INTEGER DEFAULT NULL REFERENCES incidents(id)
);

-- NOTE: no index on alerts(incident_id) here — on pre-012 databases the
-- alerts table exists without the column (CREATE TABLE IF NOT EXISTS is a
-- no-op) and the index statement would abort initialization before the
-- migration runner could add the column.  Migration 012 creates it.

-- =============================================================================
-- INCIDENTS TABLE (Phase 2, AI-first)
-- =============================================================================
-- Fused groups of related alerts: alerts hitting the same device (or the
-- network at large) inside a rolling window share one incident.
-- Maintained by intelligence.incidents.IncidentManager via migration 012.

CREATE TABLE IF NOT EXISTS incidents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'resolved')),
    severity TEXT NOT NULL DEFAULT 'info'
        CHECK(severity IN ('info', 'low', 'medium', 'warning', 'high', 'critical')),
    title TEXT NOT NULL,
    device_mac TEXT DEFAULT NULL,    -- NULL = network-wide
    alert_count INTEGER NOT NULL DEFAULT 0,
    categories TEXT DEFAULT NULL,    -- JSON array of alert types
    summary TEXT DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_incidents_status_updated
    ON incidents(status, updated_at);

-- =============================================================================
-- BLOCKING_RULES TABLE
-- =============================================================================
-- Admin policy for what connected clients may reach. Enforced by
-- packet_capture.dns_blocker, which answers a matching client DNS query with
-- NXDOMAIN before the real reply arrives. Added by migration 013.

CREATE TABLE IF NOT EXISTS blocking_rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    domain TEXT NOT NULL,
    device_mac TEXT DEFAULT NULL,    -- NULL = every client
    enabled INTEGER NOT NULL DEFAULT 1,
    hit_count INTEGER NOT NULL DEFAULT 0,
    last_hit TIMESTAMP DEFAULT NULL,
    note TEXT DEFAULT NULL
);

-- COALESCE keeps the network-wide rule distinct from per-device ones: NULLs
-- never compare equal, so a plain UNIQUE(domain, device_mac) would allow
-- unlimited duplicate network-wide rules for the same domain.
CREATE UNIQUE INDEX IF NOT EXISTS idx_blocking_rules_unique
    ON blocking_rules(domain, COALESCE(device_mac, ''));

CREATE INDEX IF NOT EXISTS idx_blocking_rules_enabled
    ON blocking_rules(enabled);

-- =============================================================================
-- BANDWIDTH_STATS TABLE
-- =============================================================================
-- Aggregated bandwidth statistics per minute for historical analysis.
-- Used for charts and trend analysis.

CREATE TABLE IF NOT EXISTS bandwidth_stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL,
    bytes_in INTEGER DEFAULT 0,
    bytes_out INTEGER DEFAULT 0,
    packets_in INTEGER DEFAULT 0,
    packets_out INTEGER DEFAULT 0,
    active_connections INTEGER DEFAULT 0,
    unique_devices INTEGER DEFAULT 0
);

-- =============================================================================
-- PROTOCOL_STATS TABLE
-- =============================================================================
-- Aggregated protocol statistics for analysis.

CREATE TABLE IF NOT EXISTS protocol_stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL,
    protocol TEXT NOT NULL,
    bytes_total INTEGER DEFAULT 0,
    packets_total INTEGER DEFAULT 0,
    connection_count INTEGER DEFAULT 0
);

-- =============================================================================
-- DAILY_USAGE TABLE
-- =============================================================================
-- Stores daily data usage per device for tracking over time.
-- Resets at midnight each day.

CREATE TABLE IF NOT EXISTS daily_usage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,              -- YYYY-MM-DD format
    mac_address TEXT NOT NULL,
    ip_address TEXT,
    device_name TEXT,
    bytes_sent INTEGER DEFAULT 0,
    bytes_received INTEGER DEFAULT 0,
    total_bytes INTEGER DEFAULT 0,
    packet_count INTEGER DEFAULT 0,
    first_seen_today TIMESTAMP,
    last_seen_today TIMESTAMP,
    UNIQUE(date, mac_address)
);

CREATE INDEX IF NOT EXISTS idx_daily_usage_date ON daily_usage(date);
CREATE INDEX IF NOT EXISTS idx_daily_usage_mac ON daily_usage(mac_address);
CREATE INDEX IF NOT EXISTS idx_daily_usage_date_mac ON daily_usage(date, mac_address);

-- =============================================================================
-- SYSTEM_CONFIG TABLE
-- =============================================================================
-- Stores system configuration and metadata.

CREATE TABLE IF NOT EXISTS system_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- INDEXES FOR PERFORMANCE
-- =============================================================================
-- Phase 4 #45: traffic_summary has 8 composite/covering indexes.
-- Single-column indexes were removed — they are strict prefixes of the
-- composite ones and only add write amplification with no read benefit.
-- See migration 006_drop_redundant_indexes.sql for details.

-- Covering composite indexes for traffic_summary
CREATE INDEX IF NOT EXISTS idx_traffic_timestamp_protocol ON traffic_summary(timestamp, protocol);
CREATE INDEX IF NOT EXISTS idx_traffic_timestamp_direction ON traffic_summary(timestamp, direction);
CREATE INDEX IF NOT EXISTS idx_traffic_control_timestamp ON traffic_summary(is_control, timestamp);
CREATE INDEX IF NOT EXISTS idx_traffic_protocol_timestamp ON traffic_summary(protocol, timestamp);
CREATE INDEX IF NOT EXISTS idx_traffic_ts_bytes_dir ON traffic_summary(timestamp, bytes_transferred, direction);
CREATE INDEX IF NOT EXISTS idx_traffic_src_ip_ts_bytes ON traffic_summary(source_ip, timestamp, bytes_transferred);
CREATE INDEX IF NOT EXISTS idx_traffic_dst_ip_ts_bytes ON traffic_summary(dest_ip, timestamp, bytes_transferred);
CREATE INDEX IF NOT EXISTS idx_traffic_src_mac_ts_bytes ON traffic_summary(source_mac, timestamp, bytes_transferred);
CREATE INDEX IF NOT EXISTS idx_traffic_dst_mac_ts_bytes ON traffic_summary(dest_mac, timestamp, bytes_transferred);

-- Device indexes
CREATE INDEX IF NOT EXISTS idx_devices_mac ON devices(mac_address);
CREATE INDEX IF NOT EXISTS idx_devices_ip ON devices(ip_address);
CREATE INDEX IF NOT EXISTS idx_devices_ipv4 ON devices(ipv4_address);
CREATE INDEX IF NOT EXISTS idx_devices_last_seen ON devices(last_seen);
CREATE INDEX IF NOT EXISTS idx_devices_active_mode ON devices(active_mode);
-- Covering index for get_active_device_count(): scans last_seen range,
-- filters by active_mode/mac_address, and projects ip_address/ipv4_address
-- without touching the main table.
CREATE INDEX IF NOT EXISTS idx_devices_count_cover ON devices(last_seen, active_mode, mac_address, ip_address, ipv4_address);

-- Alert indexes
CREATE INDEX IF NOT EXISTS idx_alerts_timestamp ON alerts(timestamp);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_type ON alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_alerts_resolved ON alerts(resolved);
CREATE INDEX IF NOT EXISTS idx_alerts_timestamp_severity ON alerts(timestamp, severity);

-- Bandwidth stats indexes
CREATE INDEX IF NOT EXISTS idx_bandwidth_timestamp ON bandwidth_stats(timestamp);

-- Protocol stats indexes
CREATE INDEX IF NOT EXISTS idx_protocol_stats_timestamp ON protocol_stats(timestamp);
CREATE INDEX IF NOT EXISTS idx_protocol_stats_protocol ON protocol_stats(protocol);

-- =============================================================================
-- TRAFFIC ROLLUP TABLE (hourly aggregation for long-term queries)
-- =============================================================================
-- Raw traffic_summary rows are aggregated here every hour, then raw rows
-- older than 24 h are deleted.  Keeps queries fast while retaining 90+ days
-- of hourly historical data.

CREATE TABLE IF NOT EXISTS traffic_rollup (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hour_bucket TEXT NOT NULL,          -- 'YYYY-MM-DD HH:00:00'
    source_ip TEXT,
    dest_ip TEXT,
    protocol TEXT,
    direction TEXT DEFAULT 'unknown',
    total_bytes INTEGER DEFAULT 0,
    packet_count INTEGER DEFAULT 0,
    UNIQUE(hour_bucket, source_ip, dest_ip, protocol, direction)
);

CREATE INDEX IF NOT EXISTS idx_rollup_hour ON traffic_rollup(hour_bucket);
CREATE INDEX IF NOT EXISTS idx_rollup_protocol ON traffic_rollup(protocol);

-- =============================================================================
-- FLOWS TABLE (Phase 0, AI-first: flow-level telemetry)
-- =============================================================================
-- One row per observed flow (5-tuple + direction), aggregated by the
-- intelligence.flow_normalizer from packet batches.  This is the primary
-- input for device-behavior learning, threat detection, and the digital
-- twin.  Indexes are deliberately minimal (see traffic_summary history:
-- excess indexes caused write amplification).

CREATE TABLE IF NOT EXISTS flows (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_seen TIMESTAMP NOT NULL,
    last_seen TIMESTAMP NOT NULL,
    source_ip TEXT NOT NULL,
    dest_ip TEXT NOT NULL,
    source_port INTEGER DEFAULT NULL,
    dest_port INTEGER DEFAULT NULL,
    protocol TEXT NOT NULL DEFAULT 'UNKNOWN',
    direction TEXT DEFAULT 'unknown',
    source_mac TEXT DEFAULT NULL,
    dest_mac TEXT DEFAULT NULL,
    bytes_total INTEGER DEFAULT 0,
    packets_total INTEGER DEFAULT 0,
    is_control INTEGER DEFAULT 0,
    duration_seconds REAL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_flows_last_seen ON flows(last_seen);
CREATE INDEX IF NOT EXISTS idx_flows_src_mac_seen ON flows(source_mac, last_seen);

-- =============================================================================
-- DNS QUERIES TABLE (Phase 0, AI-first: DNS telemetry)
-- =============================================================================
-- Queried names per device — input for behavior profiles, DNS-tunneling
-- detection, and investigation retrieval.

CREATE TABLE IF NOT EXISTS dns_queries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL,
    source_ip TEXT DEFAULT NULL,
    source_mac TEXT DEFAULT NULL,
    qname TEXT NOT NULL,
    qtype INTEGER DEFAULT NULL,
    protocol TEXT DEFAULT 'DNS'
);

CREATE INDEX IF NOT EXISTS idx_dns_queries_timestamp ON dns_queries(timestamp);
CREATE INDEX IF NOT EXISTS idx_dns_queries_qname ON dns_queries(qname);

-- =============================================================================
-- BEHAVIOR PROFILES TABLE (Phase 1, AI-first: per-device learned baselines)
-- =============================================================================
-- Welford running statistics per (device, hour-of-week, metric) — lets the
-- BehaviorAnalyzer learn "normal" per device without storing raw history.

CREATE TABLE IF NOT EXISTS behavior_profiles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    mac_address TEXT NOT NULL,
    hour_of_week INTEGER NOT NULL,   -- 0-167 (weekday*24 + hour)
    metric TEXT NOT NULL,            -- bytes / flows / unique_dests / dns_queries
    count INTEGER NOT NULL DEFAULT 0,
    mean REAL NOT NULL DEFAULT 0,
    m2 REAL NOT NULL DEFAULT 0,      -- Welford sum of squared deltas
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(mac_address, hour_of_week, metric)
);

CREATE INDEX IF NOT EXISTS idx_behavior_profiles_mac ON behavior_profiles(mac_address);

-- =============================================================================
-- ALERT RULES TABLE (user-defined custom alert rules)
-- =============================================================================

CREATE TABLE IF NOT EXISTS alert_rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    metric TEXT NOT NULL CHECK(metric IN ('bandwidth_bps', 'device_count', 'packet_rate', 'protocol_bytes')),
    operator TEXT NOT NULL CHECK(operator IN ('>', '<', '>=', '<=', '==')),
    threshold REAL NOT NULL,
    severity TEXT NOT NULL DEFAULT 'warning' CHECK(severity IN ('info', 'warning', 'critical')),
    enabled INTEGER NOT NULL DEFAULT 1,
    cooldown_seconds INTEGER NOT NULL DEFAULT 300,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_triggered_at TIMESTAMP DEFAULT NULL
);

-- =============================================================================
-- DEVICE POLICIES TABLE (W5 — parental controls / quotas)
-- =============================================================================
-- Per-client controls enforced (in hotspot mode) by the DNS blocker.
CREATE TABLE IF NOT EXISTS device_policies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    device_mac TEXT NOT NULL UNIQUE,
    paused INTEGER NOT NULL DEFAULT 0,
    daily_quota_mb INTEGER DEFAULT NULL,
    blocked_windows TEXT DEFAULT NULL,   -- JSON: [{"start":"22:00","end":"07:00"}]
    note TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- DEFAULT SYSTEM CONFIGURATION
-- =============================================================================

INSERT OR IGNORE INTO system_config (key, value) VALUES ('schema_version', '1.0.0');
INSERT OR IGNORE INTO system_config (key, value) VALUES ('created_at', datetime('now'));
INSERT OR IGNORE INTO system_config (key, value) VALUES ('last_cleanup', datetime('now'));
