--
-- schema.sql - NetWatch Database Schema
-- =======================================
--
-- This file defines the database schema for NetWatch.
-- Production-ready schema with full table definitions, indexes, and constraints.
--

-- =============================================================================
-- DEVICES TABLE
-- =============================================================================
-- Stores information about devices seen on the network.
-- Each unique IP address gets one record. Updated as traffic is captured.

CREATE TABLE IF NOT EXISTS devices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ip_address TEXT NOT NULL UNIQUE,
    hostname TEXT DEFAULT NULL,
    mac_address TEXT DEFAULT NULL,
    device_name TEXT DEFAULT NULL,
    vendor TEXT DEFAULT NULL,
    first_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_bytes_sent INTEGER DEFAULT 0,
    total_bytes_received INTEGER DEFAULT 0,
    total_packets INTEGER DEFAULT 0,
    is_local INTEGER DEFAULT 0,
    device_type TEXT DEFAULT 'unknown',
    notes TEXT DEFAULT NULL
);

-- =============================================================================
-- TRAFFIC_SUMMARY TABLE
-- =============================================================================
-- Stores individual packet/connection records for traffic analysis.
-- This is the main table for bandwidth and protocol analysis.

CREATE TABLE IF NOT EXISTS traffic_summary (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_ip TEXT NOT NULL,
    dest_ip TEXT NOT NULL,
    source_mac TEXT DEFAULT NULL,
    dest_mac TEXT DEFAULT NULL,
    source_port INTEGER DEFAULT NULL,
    dest_port INTEGER DEFAULT NULL,
    protocol TEXT NOT NULL DEFAULT 'UNKNOWN',
    raw_protocol TEXT DEFAULT NULL,
    bytes_transferred INTEGER NOT NULL DEFAULT 0,
    packets_count INTEGER DEFAULT 1,
    direction TEXT DEFAULT 'unknown',
    session_id TEXT DEFAULT NULL,
    device_name TEXT DEFAULT NULL,
    vendor TEXT DEFAULT NULL
);

-- =============================================================================
-- ALERTS TABLE
-- =============================================================================
-- Stores alerts generated by the anomaly detection system.
-- Supports different severity levels and resolution tracking.

CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alert_type TEXT NOT NULL CHECK(alert_type IN ('bandwidth', 'anomaly', 'device_count', 'health', 'protocol', 'connection', 'security')),
    severity TEXT NOT NULL CHECK(severity IN ('info', 'low', 'medium', 'warning', 'high', 'critical')),
    message TEXT NOT NULL,
    details TEXT DEFAULT NULL,
    source_ip TEXT DEFAULT NULL,
    dest_ip TEXT DEFAULT NULL,
    resolved INTEGER DEFAULT 0,
    resolved_at TIMESTAMP DEFAULT NULL,
    resolved_by TEXT DEFAULT NULL,
    acknowledged INTEGER DEFAULT 0,
    acknowledged_at TIMESTAMP DEFAULT NULL
);

-- =============================================================================
-- BANDWIDTH_STATS TABLE
-- =============================================================================
-- Aggregated bandwidth statistics per minute for historical analysis.
-- Used for charts and trend analysis.

CREATE TABLE IF NOT EXISTS bandwidth_stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL,
    bytes_in INTEGER DEFAULT 0,
    bytes_out INTEGER DEFAULT 0,
    packets_in INTEGER DEFAULT 0,
    packets_out INTEGER DEFAULT 0,
    active_connections INTEGER DEFAULT 0,
    unique_devices INTEGER DEFAULT 0
);

-- =============================================================================
-- PROTOCOL_STATS TABLE
-- =============================================================================
-- Aggregated protocol statistics for analysis.

CREATE TABLE IF NOT EXISTS protocol_stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL,
    protocol TEXT NOT NULL,
    bytes_total INTEGER DEFAULT 0,
    packets_total INTEGER DEFAULT 0,
    connection_count INTEGER DEFAULT 0
);

-- =============================================================================
-- DAILY_USAGE TABLE
-- =============================================================================
-- Stores daily data usage per device for tracking over time.
-- Resets at midnight each day.

CREATE TABLE IF NOT EXISTS daily_usage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,              -- YYYY-MM-DD format
    mac_address TEXT NOT NULL,
    ip_address TEXT,
    device_name TEXT,
    bytes_sent INTEGER DEFAULT 0,
    bytes_received INTEGER DEFAULT 0,
    total_bytes INTEGER DEFAULT 0,
    packet_count INTEGER DEFAULT 0,
    first_seen_today TIMESTAMP,
    last_seen_today TIMESTAMP,
    UNIQUE(date, mac_address)
);

CREATE INDEX IF NOT EXISTS idx_daily_usage_date ON daily_usage(date);
CREATE INDEX IF NOT EXISTS idx_daily_usage_mac ON daily_usage(mac_address);
CREATE INDEX IF NOT EXISTS idx_daily_usage_date_mac ON daily_usage(date, mac_address);

-- =============================================================================
-- SYSTEM_CONFIG TABLE
-- =============================================================================
-- Stores system configuration and metadata.

CREATE TABLE IF NOT EXISTS system_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- INDEXES FOR PERFORMANCE
-- =============================================================================

-- Traffic summary indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_traffic_timestamp ON traffic_summary(timestamp);
CREATE INDEX IF NOT EXISTS idx_traffic_source_ip ON traffic_summary(source_ip);
CREATE INDEX IF NOT EXISTS idx_traffic_dest_ip ON traffic_summary(dest_ip);
CREATE INDEX IF NOT EXISTS idx_traffic_protocol ON traffic_summary(protocol);
CREATE INDEX IF NOT EXISTS idx_traffic_source_port ON traffic_summary(source_port);
CREATE INDEX IF NOT EXISTS idx_traffic_dest_port ON traffic_summary(dest_port);
CREATE INDEX IF NOT EXISTS idx_traffic_timestamp_protocol ON traffic_summary(timestamp, protocol);
CREATE INDEX IF NOT EXISTS idx_traffic_direction ON traffic_summary(direction);
CREATE INDEX IF NOT EXISTS idx_traffic_source_mac ON traffic_summary(source_mac);
CREATE INDEX IF NOT EXISTS idx_traffic_dest_mac ON traffic_summary(dest_mac);

-- Composite indexes for device detail queries (source_ip + timestamp, dest_ip + timestamp)
CREATE INDEX IF NOT EXISTS idx_traffic_src_ip_ts ON traffic_summary(source_ip, timestamp);
CREATE INDEX IF NOT EXISTS idx_traffic_dst_ip_ts ON traffic_summary(dest_ip, timestamp);

-- Device indexes
CREATE INDEX IF NOT EXISTS idx_devices_ip ON devices(ip_address);
CREATE INDEX IF NOT EXISTS idx_devices_last_seen ON devices(last_seen);
CREATE INDEX IF NOT EXISTS idx_devices_mac ON devices(mac_address);

-- Alert indexes
CREATE INDEX IF NOT EXISTS idx_alerts_timestamp ON alerts(timestamp);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_type ON alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_alerts_resolved ON alerts(resolved);
CREATE INDEX IF NOT EXISTS idx_alerts_timestamp_severity ON alerts(timestamp, severity);

-- Bandwidth stats indexes
CREATE INDEX IF NOT EXISTS idx_bandwidth_timestamp ON bandwidth_stats(timestamp);

-- Protocol stats indexes
CREATE INDEX IF NOT EXISTS idx_protocol_stats_timestamp ON protocol_stats(timestamp);
CREATE INDEX IF NOT EXISTS idx_protocol_stats_protocol ON protocol_stats(protocol);

-- =============================================================================
-- TRAFFIC ROLLUP TABLE (hourly aggregation for long-term queries)
-- =============================================================================
-- Raw traffic_summary rows are aggregated here every hour, then raw rows
-- older than 24 h are deleted.  Keeps queries fast while retaining 90+ days
-- of hourly historical data.

CREATE TABLE IF NOT EXISTS traffic_rollup (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hour_bucket TEXT NOT NULL,          -- 'YYYY-MM-DD HH:00:00'
    source_ip TEXT,
    dest_ip TEXT,
    protocol TEXT,
    direction TEXT DEFAULT 'unknown',
    total_bytes INTEGER DEFAULT 0,
    packet_count INTEGER DEFAULT 0,
    UNIQUE(hour_bucket, source_ip, dest_ip, protocol, direction)
);

CREATE INDEX IF NOT EXISTS idx_rollup_hour ON traffic_rollup(hour_bucket);
CREATE INDEX IF NOT EXISTS idx_rollup_protocol ON traffic_rollup(protocol);

-- =============================================================================
-- ALERT RULES TABLE (user-defined custom alert rules)
-- =============================================================================

CREATE TABLE IF NOT EXISTS alert_rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    metric TEXT NOT NULL CHECK(metric IN ('bandwidth_bps', 'device_count', 'packet_rate', 'protocol_bytes')),
    operator TEXT NOT NULL CHECK(operator IN ('>', '<', '>=', '<=', '==')),
    threshold REAL NOT NULL,
    severity TEXT NOT NULL DEFAULT 'warning' CHECK(severity IN ('info', 'warning', 'critical')),
    enabled INTEGER NOT NULL DEFAULT 1,
    cooldown_seconds INTEGER NOT NULL DEFAULT 300,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_triggered_at TIMESTAMP DEFAULT NULL
);

-- =============================================================================
-- DEFAULT SYSTEM CONFIGURATION
-- =============================================================================

INSERT OR IGNORE INTO system_config (key, value) VALUES ('schema_version', '1.0.0');
INSERT OR IGNORE INTO system_config (key, value) VALUES ('created_at', datetime('now'));
INSERT OR IGNORE INTO system_config (key, value) VALUES ('last_cleanup', datetime('now'));
